### ISSUE TITLE
paging vs filter

### ISSUE THREAD

**Issue by lubop** [PedroBegosso/filter_results#1]
Hey, first of all, great job. Your filter_results is great. 
But one issue occurred after implementing to the long list index with paging. 
I've got like 200 records with first name and last name and applied default cake paging and using filter_result. Everything is great, but when I'm on for example 6th page in paging, and then I want to filter for example by First Name entering 'John'  which is like 10 search results, the page says on the 6th page and paging, even there is only one with results. The results are only on page 1 and there is no way to get there. So the filter_result work well only is I'm using it from fist paging page. Is there chance to fix it?

**Comment by PedroBegosso** [comment]
Thanks! =)

OK, I undestand the problem and I'm going to make a fix.
When available, I notice you

**Comment by PedroBegosso** [comment]
Hi Man,
The fix is available. Clone the filter_results again and enjoy. =D

**Comment by lubop** [comment]
That was quick :) Thanks man. Now working as expected. 
Cheers.
