### ISSUE TITLE
Search + FilterResults – Need some advice.

### ISSUE THREAD

**Issue by robksawyer** [PedroBegosso/filter_results#12]
I've started a thread over at the Search plugin that I'm using asking the same thing, but basically, I'm running into some issues when using the two plugins together and could use some advice. Basically, what am I doing wrong? I'm using the branch 2.3 of FilterResults and the latest rev of Search. See https://github.com/CakeDC/search/issues/97 for more.

**Comment by PedroBegosso** [comment]
Entered in the link, it looks like you solved the issue...
