### ISSUE TITLE
should be compatible with FormHelper::submit

### ISSUE THREAD

**Issue by djsamz** [PedroBegosso/filter_results#2]
what wrong? i get this massage:

Strict (2048): Declaration of FilterFormHelper::submit() should be compatible with FormHelper::submit($caption = NULL, $options = Array) [APP\Plugin\filter_results\View\Helper\FilterFormHelper.php, line 264]

thks before

**Comment by PedroBegosso** [comment]
Hello @djsamz,
Is it running in CakePHP 2.0 or 1.3?

**Comment by nolliejay** [comment]
Good day @djsamz and @pedroelsner 

I am getting the same error too

I am setting up filter results on a fresh cakephp copy. Its version is 2.2.3

**Comment by djsamz** [comment]
Good day @pedroelsner  and @nolliejay 

Soory late to answer,  same like @nolliejay running in cake 2.2.3 too.

**Comment by nesmrtelny** [comment]
Hi, I have also noticed this problem.

Not sure, if it is clear sulution, but for me worked following:

Open file:
/app/Plugin/FilterResults/View/Helper/FilterFormHelper.php

Change 

```
public function submit($name, $settings = array()) {

        if (!$this->_hasComponent()) {
            return '';
        }

        return parent::submit($name, $settings);

    }
```

With this:

```
    public function submit($name = null, $settings = array()) {

        $caption = $name;
        $options = $settings;

        if (!$this->_hasComponent()) {
                return '';
        }

        return parent::submit($caption, $options);

    }
```

**Comment by PedroBegosso** [comment]
@nesmrtelny, @djsamz and @nolliejay the plugin has been updated.

(after 4 months.... sorry man)
