### ISSUE TITLE
FilterForm Helper is generating White spaces at top of the page

### ISSUE THREAD

**Issue by ksrmcse** [PedroBegosso/filter_results#4]
Hi,

An empty line is being generated after body tag like below when I use this plugin.

&lt;body&gt;﻿
"
   &nbsp;        "
&lt;meta http-equiv="Content-Type" content="text/html; charset=utf-8"&gt;﻿

I figured that It occurs only when I add FilterForm helper in controller as 

public $helpers = array(
    'FilterResults.FilterForm' => array(
        'operators' => array(
            'LIKE'       => 'containing',
            'NOT LIKE'   => 'not containing',
            'LIKE BEGIN' => 'starting with',
            'LIKE END'   => 'ending with',
            '='  => 'equal to',
            '!=' => 'different',
            '>'  => 'greater than',
            '>=' => 'greater or equal to',
            '<'  => 'less than',
            '<=' => 'less or equal to'
        )
    )
);

Please help. Many Thanks in advance.

**Comment by PedroBegosso** [comment]
What is your cakephp version?

**Comment by ksrmcse** [comment]
Its 2.x

**Comment by ksrmcse** [comment]
Hi Pedroelsner, 

can you please suggest any resolution for it. I am using this plugin in cakephp 2.2.4 version. 

Thanks in Advance

**Comment by PedroBegosso** [comment]
I don't have any idea...
I'm try and use this on CakePHP 2.2, 2.3 and 2.4 and this error don't happen...
