### ISSUE TITLE
Missing files/.swp file for free ?

### ISSUE THREAD

**Issue by redrick** [PedroBegosso/filter_results#6]
hi there,

I am kinda trying your plugin, but man there is a whole chunk of code missing, file FilterResultsComponent.php is nowhere to find (I will try later commits...) and helper is a .swp file.... i am missing those babies :D please help me resolve it, looks useful, thumbs up :)

**Comment by PedroBegosso** [comment]
@redrick The version 2.3 change file FilterResultsComponent to FilterComponent, and FilterFormHelper to SeachFormHelp. See the new documentation: https://github.com/pedroelsner/filter_results/tree/2.3
