### ISSUE TITLE
Problema na codificação

### ISSUE THREAD

**Issue by eduardoves** [PedroBegosso/filter_results#9]
Sou iniciante em cakephp e estou tentando utilizar o plugin FilterResults mas quando inseri no meu projeto toda a codificação foi alterada, onde há acentuação esta assim �. Meu projeto está configurado como iso-8859-1. O que será que pode ter acontecido?

**Comment by eduardoves** [comment]
Consegui resolver, era um caracter estranho no começo do arquivo SearchHelper.php removi e resolveu o problema. Não entendi como apareceu, pois olhei no arquivo zipado baixado daqui e está normal.

**Comment by PedroBegosso** [comment]
Beleza! @eduardoves
